### ISSUE TITLE
Conversion from int to juce::Thread::Priority not allowed

### ISSUE THREAD

**Issue by propeller3D** [cpr2323/juce_serialport#12]
In juce_serialport.h lines 218 and 256 it says it can't convert from int to juce::Thread::Priority. I changed the argument "priority" from int to "juce::Thread::Priority" and it seems to work.

**Comment by cpr2323** [comment]
The library now expects the latest JUCE, but can be configured for the previous Thread API by defining the compile time constant `USING_JUCE_PRIOR_TO_7_0_5`
